### ISSUE TITLE
Error: Invalid tar header. Maybe the tar is corrupted or it needs to be gunzipped?

### ISSUE THREAD

**Issue by ScubaDrew** [npm/pneumatic-tubes#9]
Experiencing an error migrating: 

```
downloading  http://npm.xxx.net:8080/@/@xxxx/product-elasticsearch/_attachments/product-elasticsearch-0.0.1.tgz
finished writing /tmp/tarballs/22b6bc9b-xxxx-46ab-a074-5c50be041afc.tgz
rewriting custom registry: http://npm.xxx.net:8080 -> https://registry.xxx.npme.io
Error in stream: Error: Invalid tar header. Maybe the tar is corrupted or it needs to be gunzipped?
    at Object.exports.decode (/usr/local/lib/node_modules/pneumatic-tubes/node_modules/tar-stream/headers.js:267:43)
    at Extract.onheader (/usr/local/lib/node_modules/pneumatic-tubes/node_modules/tar-stream/extract.js:123:39)
    at Extract._write (/usr/local/lib/node_modules/pneumatic-tubes/node_modules/tar-stream/extract.js:249:8)
    at Extract._continue (/usr/local/lib/node_modules/pneumatic-tubes/node_modules/tar-stream/extract.js:212:28)
    at oncontinue (/usr/local/lib/node_modules/pneumatic-tubes/node_modules/tar-stream/extract.js:67:10)
    at Extract.ondrain (/usr/local/lib/node_modules/pneumatic-tubes/node_modules/tar-stream/extract.js:87:5)
    at Extract._write (/usr/local/lib/node_modules/pneumatic-tubes/node_modules/tar-stream/extract.js:249:8)
    at Extract._continue (/usr/local/lib/node_modules/pneumatic-tubes/node_modules/tar-stream/extract.js:212:28)
    at oncontinue (/usr/local/lib/node_modules/pneumatic-tubes/node_modules/tar-stream/extract.js:67:10)
    at onunlock (/usr/local/lib/node_modules/pneumatic-tubes/node_modules/tar-stream/extract.js:73:24)
events.js:183
      throw er; // Unhandled 'error' event
```

**Comment by RyanTheAllmighty** [comment]
This has caused me constant issues also. Looks like it's caused when the package.json file is modified to change the registry url. But only on some files.

I haven't found a solution, except to just exclude those packages having issues

**Comment by RyanTheAllmighty** [comment]
I solved this by changing the `lib/transform-tarball.js` file with the patch below:

```diff
diff --git a/lib/transform-tarball.js b/lib/transform-tarball.js
index cac7597..0376cba 100644
--- a/lib/transform-tarball.js
+++ b/lib/transform-tarball.js
@@ -77,8 +77,7 @@ async function transformTarball (tarball, {
               outBuffer.put(JSON.stringify(pkg, null, 2) + '\n', 'utf8')
             }
             outBuffer.stop()
-            header.size = outBuffer.size()
-            outBuffer.pipe(pack.entry(header, callback))
+            outBuffer.pipe(pack.entry({ ...header, size: outBuffer.size() }, callback))
           })
       } else {
         // Forward the entry into the new tarball unmodified.
```

Seems to now work fine for me
